### ISSUE TITLE
Mac M1 ARM packages architecture 

### ISSUE THREAD

**Issue by ClementGold** [insarlab/MintPy#1002]
Dear All, 

I wanted to use the packages MintPy because the complementary with ASF data is looking really promessing but seems to what I read the packages in ARM architecture is not deploy i'm right ? 

The other option will use a dockers on a different system, i don't know if anyone here have tested this option and what people with arm architecture choose . 

Best regards, 
Clément

**Comment by yunjunz** [comment]
Hi Clément, mintpy installation through `conda-forge/arm64` channel is not supported (https://github.com/insarlab/MintPy/issues/870), because `pysolid`, one of mintpy's dependencies, is architecture dependent and not available for arm64 channel yet.

With an Apple silicon chip, it's still fine to install an x86_64 architecture version of conda/mamba (at the cost of less efficient computing, which I did not compare and notice). That's what I am doing with my Mac M2 machine.

**Comment by ClementGold** [comment]
> Hi Clément, mintpy installation through `conda-forge/arm64` channel is not supported (#870), because `pysolid`, one of mintpy's dependencies, is architecture dependent and not available for arm64 channel yet.
> 
> With an Apple silicon chip, it's still fine to install an x86_64 architecture version of conda/mamba (at the cost of less efficient computing, which I did not compare and notice). That's what I am doing with my Mac M2 machine.

Hi yunjunz, 

Thanks for the quick reply I will doing with this system maybe. 
I learn also with ec2 machine linux is possible with cloud system so it's maybe better to use linux in this way with conda install. 

Best, 
Clément

**Comment by yunjunz** [comment]
Close this issue since it's answered and duplicated with #870.
