### ISSUE TITLE
new features for save_gbis.py

### ISSUE THREAD

**Issue by yunjunz** [insarlab/MintPy#187]
@ranneylxr, @falkamelung, let's discuss here regarding new features for save_gbis.py #174, https://github.com/geodesymiami/mimtpy/issues/1. I can think of the following:

The input requirement for GBIS is simple: displacement measurement in points format and in the unit of radians.

1. support for more file types: currently supports velocity and *.unw file, which is generated using save_roipac.py. HDF-EOS5, timeseries and ifgramStack file supports are desired.

2. regarding multiple tracks of datasets, I don't think it's a good idea to include it in save_gbis.py, because GBIS handles each track of dataset in a separate mat file, thus, for multiple mat files, one can run save_gbis.py multiple times. Merging mutiple tracks in one command line would bring unnecessary complexity.

What do you think?

**Comment by ditafaith** [comment]
Hello @yunjunz @falkamelung and others,
I use save_gbis to get input files for further stages. 
However, I got an error in GBIS due to input files are one element, as shown below. On the other side, the example data showed two elements. Could you give me a hint of this issue ?

![Screenshot from 2023-12-29 21-14-42](https://github.com/insarlab/MintPy/assets/126780178/0e5172d8-56a4-4a8f-a050-eb5e1cebb04d)
