### ISSUE TITLE
save_kmz_timeseries.py output can't be opened

### ISSUE THREAD

**Issue by ehavazli** [insarlab/MintPy#342]
output from save_kmz_timeseries.py can't be opened by Google Earth or a text editor. Google Earth returns the error:
<img width="416" alt="Screen Shot 2020-05-10 at 2 24 23 PM" src="https://user-images.githubusercontent.com/6526589/81511014-1e255180-92cb-11ea-8f78-851b83ecfecf.png">

When you want to open the file with a text editor:

<img width="434" alt="Screen Shot 2020-05-10 at 2 33 34 PM" src="https://user-images.githubusercontent.com/6526589/81511031-42812e00-92cb-11ea-80fb-962922f4f119.png">

- I am using ARIA products so all the files are already geocoded.

**Full script that generated the error**

```
save_kmz_timeseries.py timeseries_ERA5_demErr.h5

save_kmz_timeseries.py timeseries_ERA5_demErr.h5 --vel velocity.h5 --tcoh temporalCoherence.h5 --mask maskTempCoh.h5
```

**Full error message**

```
output file is created without an error message
```

**System information**

* Operating system: macOS Mojave 10.14.6 
* Version of Python and relevant dependencies if applicable : Python 3.6.7
* Version of MintPy (output of `smallbaselineApp.py -v`): MintPy release version v1.2.2-29, release date 2020-05-10
* Your custom / default template file (`smallbaselineApp.cfg`): None

**Comment by ehavazli** [comment]
Update: 
- The output works with a smaller data set, the problem seems to be related to file

**Comment by yunjunz** [comment]
Interesting issue. @ehavazli could you provide more detailed info about the data file size and resulting kmz file size?

**Comment by ehavazli** [comment]
**timeseries file**
Size: 6.21GB
Number of acquisitions: 115
NUMBER_OF_PAIRS: 373
WIDTH: 3859
FILE_LENGTH: 3429

**KMZ file**
Size: 2.3GB
Steps: 20 5 2 (default) 
- The output file can't be read

Size: 587.2MB
Steps: 100 25 10
- The output file is successfully rendered by GE but resolution is too low.

**Comment by yunjunz** [comment]
This does not seem like to be a bug in the script but a limiting issue in the Google Earth's side. 

@ehavazli if you really want to use the google earth feature for your dataset, I would recommend playing with the step option, you could check the [doc](https://mintpy.readthedocs.io/en/latest/google_earth/) for details.

@Ovec8hkin since this is not the first time we heard issue with the google earth limit, do you think it's possible for you to write down some information, links and/or numbers on the doc regarding the limit? This will better inform the one who is using it so that he/she could be more aware of this potential issue.

**Comment by Ovec8hkin** [comment]
I can try to look around for some legitimate documentation,  but from what I remember a lot of the Google Earth “limits” are heresay reported by the developer community.

**Comment by yunjunz** [comment]
More comments are added in the commit https://github.com/insarlab/MintPy/pull/353/commits/0c969bc.
