### ISSUE TITLE
Overflow Error In Stack.py due to np.int32 value

### ISSUE THREAD

**Issue by pbrotoisworo** [insarlab/MintPy#536]
I have noticed that there is a possible bug where it can lead to an overflow error due to `np.sum()` returning a `np.int32` object. This is fixed if it is cast as a float object.

It is in this specific line:
https://github.com/insarlab/MintPy/blob/main/mintpy/objects/stack.py#L1035

I have replicated the variables in my analysis. I am analyzing 75 interferograms using MintPy.

```python
# Parameters specific to my analysis
self.length = 1845
self.width = 1370
ds_size = np.sum(75) * self.length * self.width * 4  # ds_size is 758295000

num_step = int(np.ceil(ds_size * 3 / (4 * 1024**3))) # num_step is zero

RuntimeWarning: overflow encountered in long_scalars
```
Expected value for num_step is `1` but due to overflow error actual value is `0`. After this, the MintPy analysis fails due to `ZeroDivisionError`.

**My Solution:**
I fixed the error by temporarily casting `ds_size` as a float32 when calculating num_step.
```python
num_step = int(np.ceil(np.float32(ds_size) * 3 / (4 * 1024**3)))
```

**Comment by yunjunz** [comment]
This seems to be a win32-only issue as [`np.sum`](https://numpy.org/doc/stable/reference/generated/numpy.sum.html) returns value in the platform integer by default. With your example above, the `4 * 1024**3` part exceeds the int32 range, rather than the `ds_size` part.

I would recommend to explicitly specify int64 directly at [stack.py#L1035](https://github.com/insarlab/MintPy/blob/main/mintpy/objects/stack.py#L1035) as `np.sum(ifgram_flag, dtype=np.int64)`. If you agree, please feel free to go ahead to issue a PR. 

There might be other places having similar issues as well.
