### ISSUE TITLE
Implement Effective Coherence Ratio Interferogram Selection

### ISSUE THREAD

**Issue by forrestfwilliams** [insarlab/MintPy#579]
**Description of the desired feature**
In InSAR time-series analyses, it is often necessary to exclude interferograms that do not meet a quality standard. MintPy has several methods for automatically selecting high quality interferograms, but I believe it would be worthwhile to implement [Kang et al's Effective Coherence Ratio](https://doi.org/10.1016/j.rse.2021.112400) method for interferogram selection. This method excludes/includes interferograms based on the proportional coverage of cells that meet a minimum coherence threshold (defined automatically as the average coherence within water regions). I am happy to lead the implementation of this feature.

**Describe the solution you'd like**
I would like to implement this interferogram selection method as another option alongside the other interferogram selection techniques in `modify_network.py`

Implementation Steps:
1. Implement Effective Coherence Ratio selection in `modify_network.py`'s `get_date12_to_drop` function
    a. Calculate the average spatial coherence for all areas included in a water mask
    b. Calculate the proportional area above average water mask coherence value in interferograms
    c. Generate list of interferograms to drop
2. Integrate this option into `smallbaselineApp.py` and `smallbaselineApp.cfg`

**Are you willing to help implement and maintain this feature?**
Yes

**References**
Kang, Y., Lu, Z., Zhao, C., Xu, Y., Kim, J. W., & Gallegos, A. J. (2021). InSAR monitoring of creeping landslides in mountainous regions: A case study in Eldorado National Forest, California. Remote Sensing of Environment, 258, 112400.

**Comment by yunjunz** [comment]
Hi @forrestfwilliams, correct me if I am wrong, from a very quick look at Kang et al. (2021), the proposed method seems close to Chaussard et al. (2015), which is where I started for the coherence-based network modification. I found the average coherence easier to understand but did not compare the two slightly different methods (average coherence vs. pixel percentage) extensively. I think it will be good for you to be aware of this. Please feel free to implement it though.

Chaussard, E., Bürgmann, R., Fattahi, H., Nadeau, R. M., Taira, T., Johnson, C. W., & Johanson, I. (2015). Potential for larger earthquakes in the East San Francisco Bay Area due to the direct connection between the Hayward and Calaveras Faults. Geophysical Research Letters, 42(8), 2734-2741. http://dx.doi.org/10.1002/2015GL063575

**Comment by forrestfwilliams** [comment]
Hi @yunjunz, thanks for pointing this out! While the two techniques are very similar, Keng et al.'s (2021) approach has some aspects that I think are worth implementing. Particularly, I like that they use the average coherence value within the water mask to define the minimum desired coherence value.
