### ISSUE TITLE
Unexpected changes while geocoding

### ISSUE THREAD

**Issue by bbuzz31** [insarlab/MintPy#736]
I've run into two issues regarding commit 70d606ee

1. I can no longer geocode a watermask (created iwth `generate_mask.py` ) as it doesn't have the heading attribute:
-```/mintpy/utils/utils0.py", line 222, in auto_lat_lon_step_size
    az_angle = np.deg2rad(abs(heading2azimuth_angle(float(atr['HEADING']))))
KeyError: 'HEADING'```

2. The size of the geocoded files (for example temporal coherence mask) is no longer consistent with the original radar coded mask (and I think width/height are flipped). Prior to this commit, the sizes were consistent. I'm not sure if this is expected or not. 
-the original size was (1504 x 3177) and is now (3213 x 1798).

Any thoughts on fixes? I can help implement.

**Comment by yunjunz** [comment]
While introducing this back-incompatible change, I thought about the potential missing metadata issue, thus, I introduced the `try/except` check to fall back to the old behavior in that scenario. Was this your case, or you had a running error? If so, could you please paste the full message here?

As we don't always know which file (source data file or lookup table file) has more complete metadata, a more robust way would be: modifying [utils0.auto_lat_lon_step_size()](https://github.com/insarlab/MintPy/blob/70d66d1bcfbd3b6115d54cbdc2bce674e7df267f/mintpy/utils/utils0.py#L206) to take a list of dict objects, searching and use the dict object with the most complete set of metadata. It would be great if you could implement this, and don't hesitate to let me know if there is any issue please.

+ The list to feed in `resample.py` is `[self.src_meta, self.lut_meta]`.

+ Here are the metadata that we should search to locate the preferred dict object:

```python
HEADING
AZIMUTH_PIXEL_SIZE
RANGE_PIXEL_SIZE
```

The file size before and after geocoding will change, and it's expected. The reason is explained in details in the commit msg.

**Comment by bbuzz31** [comment]
Thanks @yunjunz I was literally in the process of editing my comment as yours poppsed up, as I just saw the commit message. Thanks for the quick response!

Regarding the first point, the program halts with the following error:
```
Traceback (most recent call last):
  File "/u/leffe-data2/buzzanga/Software_InSAR/MintPy_git/mintpy/geocode.py", line 376, in <module>
    main(sys.argv[1:])
  File "/u/leffe-data2/buzzanga/Software_InSAR/MintPy_git/mintpy/geocode.py", line 369, in main
    run_geocode(inps)
  File "/u/leffe-data2/buzzanga/Software_InSAR/MintPy_git/mintpy/geocode.py", line 273, in run_geocode
    res_obj.prepare()
  File "/u/leffe-data2/buzzanga/Software_InSAR/MintPy_git/mintpy/objects/resample.py", line 170, in prepare
    self.prepare_geometry_definition_radar()
  File "/u/leffe-data2/buzzanga/Software_InSAR/MintPy_git/mintpy/objects/resample.py", line 343, in prepare_geome
try_definition_radar
    lat_step, lon_step = ut.auto_lat_lon_step_size(self.src_meta, lat_c)
  File "/u/leffe-data2/buzzanga/Software_InSAR/MintPy_git/mintpy/utils/utils0.py", line 222, in auto_lat_lon_step
_size
    az_angle = np.deg2rad(abs(heading2azimuth_angle(float(atr['HEADING']))))
KeyError: 'HEADING'
```
I'll take a more detailed look tomorrow and see why the `try/except` check isn't working

**Comment by bbuzz31** [comment]
Hi @yunjunz, the reason the try except error isn't working is because there is a `KeyError` getting thrown and the current formulation is set to catch an `AttributeError`.
- Simply fixed by changing `except AttributeError:` to `except KeyError:`

For searching the metadata we would prefer to use the `self.src_meta` over `self.lut_meta` yes?
Alternatively, could we just create a new merged dictionary with all the metadata  the two dictionary and pass that to the [auto_lat_lon_step_size()](https://github.com/insarlab/MintPy/blob/70d66d1bcfbd3b6115d54cbdc2bce674e7df267f/mintpy/utils/utils0.py#L206) 

e.g., 
```
dct_meta = self.lut_meta.copy() # don't mess with the original dictionaries
dct_meta.update(self.src_meta) # overwrites values with identical keys 
lat_c = (src_lat0 + src_lat1) / 2.
lat_step, lon_step = ut.auto_lat_lon_step_size(dct_meta, lat_c)
```

**Comment by yunjunz** [comment]
Hi @bbuzz31, your solution of using `KeyError` and "merging dictionaries" sounds great! Could you issue a PR for it?

My only suggestion is to use `meta = {**self.src_meta, **self.lut_meta}` to merge the dictionaries, as `self.lut_meta.copy()` is not a deep copy (https://stackoverflow.com/questions/2465921/how-to-copy-a-dictionary-and-only-edit-the-copy).

**Comment by bbuzz31** [comment]
Great, will do.
